services:
  scraper:
    build: "."
    image: "scraper"
    container_name: marketplace_scraper
    volumes:
      - <host-path>:/app/config/keywords.py
    ports:
      - "9184:5000"  # Webserver port
    restart: always
    environment:
      URL:
      TO_EMAIL:
      TO_PSWD:
      FROM_EMAIL:
      FROM_PSWD:
